image: ruby:3.1.2
stages:
  - test
.base_setup:
  before_script:
    - gem install json
    - bundle install
    - cd spec/dummy && bundle exec rake db:create db:migrate db:seed
    - RAILS_ENV=test bin/rails db:create db:migrate
    - cd ../../

run_tests:
  stage: test
  extends: .base_setup
  script:
    - bundle exec rspec
  tags:
    - docker
