require:
  - rubocop-rails
  - rubocop-rspec

Rails:
   Enabled: true

AllCops:
  DisplayCopNames: true
  DisplayStyleGuide: true
  ExtraDetails: true
  DefaultFormatter: html
  TargetRubyVersion: 3.1.0
  Exclude:
     - bin/**/*
     - vendor/**/*
     - tmp/**/*
     - spec/dummy/db/**/*
     - Gemfile*
     - .simplecov
     - spec/swagger_helper.rb
     - lib/tasks/auto_annotate_models.rake

Layout/LineLength:
  Enabled: true
  Max: 100

# Indentation
Layout/IndentationStyle:
  Enabled: true
  EnforcedStyle: tabs

Layout/IndentationWidth:
  Enabled: true
  Width: 1

# Layout
Layout/CommentIndentation:
  Enabled: true
  AllowForAlignment: true

Layout/HashAlignment:
  Enabled: true

Layout/MultilineMethodCallIndentation:
  Enabled: true
  EnforcedStyle: indented

Layout/FirstParameterIndentation:
  Enabled: true

Layout/FirstArrayElementIndentation:
  Enabled: false

Layout/FirstArgumentIndentation:
  Enabled: false

Layout/ClosingParenthesisIndentation:
  Enabled: false

Layout/ParameterAlignment:
  Enabled: true
  EnforcedStyle: with_fixed_indentation

Layout/FirstHashElementIndentation:
  Enabled: false

Layout/AccessModifierIndentation:
  Enabled: true
  EnforcedStyle: outdent

Layout/SpaceInsideArrayLiteralBrackets:
  Enabled: true

Layout/SpaceInsideReferenceBrackets:
  Enabled: true

Layout/SpaceInsideParens:
  Enabled: true

Layout/SpaceInsideRangeLiteral:
  Enabled: true

Layout/SpaceAroundBlockParameters:
  Enabled: true

Layout/SpaceInsidePercentLiteralDelimiters:
  Enabled: true

Layout/CaseIndentation:
  Enabled: true
  EnforcedStyle: end

# Style
Style/FrozenStringLiteralComment:
  Enabled: false

Style/AutoResourceCleanup:
  Enabled: true

Style/LambdaCall:
  Enabled: true

Style/Documentation:
  Enabled: false

# Rails
Rails/FilePath:
   EnforcedStyle: arguments

# RSpec
RSpec/MultipleMemoizedHelpers:
  Enabled: false

RSpec/FilePath:
  Enabled: false

RSpec/NestedGroups:
  Enabled: true
  Max: 4

RSpec/ExampleWording:
  Enabled: true

RSpec/ContextWording:
  Enabled: true
  Prefixes:
    - when
    - with
    - without
    - if
    - unless
    - for
    - post
    - get
    - delete
    - patch
    - swagger
    - and
    - stub

Metrics/BlockLength:
  Enabled: true
  Exclude:
     - spec/**/*

Naming/PredicateName:
  Enabled: false
